version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rukshani
    ports:
      - "3306:3306"
